version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: froweey/droneautocancel:latest
    container_name: web
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - webnet
networks:
  webnet: